    <script type='text/javascript' src="/assets/js/ajax_tools.js"></script>
    <script type='text/javascript' src="/assets/js/dev_helper.js"></script>
    <script type='text/javascript' src="/assets/js/update_numbers.js"></script>
    <script type='text/javascript' src="/assets/js/range_field.js"></script>
    <script type='text/javascript' src="/assets/js/slide_ui.js"></script>
    <script type='text/javascript' src="/assets/js/update_report_anywhere.js"></script>
    <script type='text/javascript' src="/assets/js/recommendation.js"></script>
    <script type='text/javascript' src="/assets/js/field_functions.js"></script>
    <script type='text/javascript' src="/assets/js/logging.js"></script>
